settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: V2Board # unique identifier
    name: V2Board
    description: 'V2Board page' # default=empty
    url: 'https://xui.jiangfff.online' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: chat-brcon
    name: chat-brcon
    description: 'chat-brcon page'
    url: 'https://chat.brcon.com.cn'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: telegraph-image
    name: telegraph-image
    description: 'telegraph-image page'
    url: 'https://image.nailao.one'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true 

  - id: vless
    name: vless
    description: 'vless'
    url: 'https://vless.jiangfff.online'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: hertzbeat
    name: hertzbeat
    description: 'hertzbeat'
    url: 'http://47.100.26.226:1157'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true  
