settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: v2board # unique identifier
    name: v2board
    description: 'v2board page' # default=empty
    url: 'https://xui.jiangfff.online' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: chat-brcon
    name: chat-brcon
    description: 'chat-brcon page'
    url: 'https://chat.brcon.com.cn'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

   - id: image
    name: image
    description: 'image page'
    url: 'https://image.nailao.one'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true  
